{% set python_min = "3.10" %}
{% set name = "modepy" %}
{% set version = "2026.1" %}
{% set sha256 = "25e0be56a109ae69ed5d73b0032c5dbeafbc8aa88552f4cb338c7fa9b98cb1d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pytools
    - pymbolic >=2024.2

test:
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - {{ name }}
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: http://pypi.python.org/pypi/modepy
  dev_url: http://github.com/inducer/modepy
  doc_url: https://documen.tician.de/modepy
  license: MIT
  license_file: LICENSE
  summary: Modes and nodes for high-order methods

extra:
  recipe-maintainers:
    - inducer
