{% set name = "modepy" %}
{% set version = "2025.1" %}
{% set sha256 = "d72597fdce3a45bddb441ccca7e23d5fce5dd9ef25749964a2da4057d2c7d898" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pytools
    - pymbolic >=2024.2

test:
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - {{ name }}
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: http://pypi.python.org/pypi/modepy
  dev_url: http://github.com/inducer/modepy
  doc_url: https://documen.tician.de/modepy
  license: MIT
  license_file: LICENSE
  summary: Modes and nodes for high-order methods

extra:
  recipe-maintainers:
    - inducer
