travis:
  secure:
    BINSTAR_TOKEN: yXIs8TNTm5F3SGokaUv0A74LolGTlXpJVEPF+G/wc+AbGVtXCxhIxCeB8WOavQbYjzZ8DZAdkYpjKwgkIZJEaq3UZVGB+nviNQGQ/2EM8OmlNskbnXIOipcf5OQgaA2DdGY+UF8+G4ql1kb1QQiCBStXT+4QVSVAxYpJ8/I1ZeaC3pxzOvpuRX5N4mb+CMcb09kH6rGkDKfekrXjpj+J+rV0LoIsYWX8pL7F9ddQWr5r0cnS3u/zP8YGYQA/gYvTmVbmJyZ9vCh6xotl8idzzKFEPM/BjIIcJDq8AASH+k+H2YHZuUQMAFi+B+w278xtLbh3ArewzniyFL6mdfqaz31giVad8opAnL/KVhc9+N1mgi8MxFeFrRDsIN2Yb2EpBlnQG8EBp1rln/PSFFsTCCugRVEyzC2xsKWCp/a7Fnsxt41y5SZX9ipoQdLIa9WGCdhpbkAQdRJPpQbWk4DHBd3tLo7/pjdaWct4u0+oUkX2ceFT6LpkJpbfycczKD61D5Q2yxpbBcDyO7ZAP6gWO7l+uX2QNi8Ir7OXIaGFYreu1dPJU1c3n/Hj0ovIONkYgQB88XgnUuNfpRszWbdOg+cE68bcFlEPgod6LqwiP1Mf8AJxkz40FQFHg12HeK6RKR+E9IuA+sJtAsNGnfvev/85QVU4ut+BgTEbjFTGOR0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
