travis:
  secure:
    BINSTAR_TOKEN: mDd5s5XGICvolLZj8mZ1Zae5n32Exs/e4AyNdZMmUPr48jfSvrOSRrQYkXCUKsL8KpJIbFRtCN2PD1/8ToiyiEwHFvGSVzdPoXsSVLA08rzkLXD6bTcD7OtISt/r/vzhu+TvAOwIUK025xxUj0Afe6/fsIdvcMHNCSWDzsFVVrxSdLbQn3bfyivUJBOAK9EnsTOC/jWRhUPa/Iynsscyyct9Br9eQQh+LR08T3G9FxAgnnFMj7f/Hzsw9PLCQIIDrowc052HHwzh7njboP8O0hG8O1DDZwwRFA1yv0tNSpDOjqUAWi9VKx+d5txmqnpGWhud3nQxhY1GYl1CRizakr+UDYBJYjViuSlt3PkTVHTK0fk5jrUI4SLfLw33CEX2xxDa1AKiYWulYkX6p7jgiwILGGgxAFLG1DxQ0ztG5p+t8/qjpYTo/G5kyBymfSrjpjOY+Pq5oaGICnuC7zR7QTe23zWQNDtiV1mqoAJWLtlxEaebd6aKCprwOZJo989BVwsya4bkwWW9uLIdsXlLTOfzSzwg6w/Rm/IMY29pOG7TO5QRk2IEI/stFX8dR6y5sfS7dPZoQNlB6DLOL7tJlF4E9X9VO+6HEABrUlDzgUGAWYog8yU5nI/8d7KXH231zdM+pFYhPUC3pNVhm2IgpuZ3mHnrQyGhyaeBR320fiY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
